# Codecov Configuration
# https://docs.codecov.com/docs/codecovyml-reference

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "71...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: 71%
        threshold: 1%

flags:
  app:
    paths:
      - fitness/
    carryforward: true

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - component_id: routers
      name: Routers
      paths:
        - fitness/routers/**
    - component_id: services
      name: Services
      paths:
        - fitness/services/**

comment:
  layout: "reach, diff, flags, components, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "**/__pycache__"
  - "**/.pytest_cache"
  - "**/tests/**"
  - "**/.venv/**"
  - "tools/**"
  - "lambda/**"
  - "terraform/**"
