# Codecov Configuration
# https://docs.codecov.com/docs/codecovyml-reference

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%

# Automated Test Selection (ATS) Configuration
# See: https://docs.codecov.com/docs/automated-test-selection-quick-start
flag_management:
  default_rules:
    carryforward_mode: labels

flags:
  tools:
    carryforward_mode: labels
    paths:
      - tools/

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "**/__pycache__"
  - "**/.pytest_cache"
  - "**/tests"
  - "**/.venv"
