FROM python:3.11-slim

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        curl \
        libatomic1 \
        nodejs=18.19.0-deb-1nodesource1 \
        npm=9.6.7-1~deb12u1 && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir pre-commit==3.7.1

WORKDIR /workspace
ENTRYPOINT ["pre-commit"]
