version: 0.2

# ================================================================
# CodeBuild - Terraform Validation
# Runs tfsec, checkov, terraform validate
# ================================================================

env:
  variables:
    TF_VERSION: "1.14.2"
    ENVIRONMENT: "dev"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing Terraform ${TF_VERSION}"
      - curl -fsSL "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip" -o terraform.zip
      - unzip -o terraform.zip -d /usr/local/bin/
      - terraform --version
      - echo "Installing tfsec"
      - curl -fsSL https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -o /usr/local/bin/tfsec
      - chmod +x /usr/local/bin/tfsec
      - echo "Installing checkov"
      - pip install checkov

  pre_build:
    commands:
      - echo "Terraform Format Check"
      - terraform fmt -check -recursive terraform/

  build:
    commands:
      - echo "Terraform Init (${ENVIRONMENT})"
      - cd "terraform/${ENVIRONMENT}"
      - terraform init -backend=false
      - echo "Terraform Validate"
      - terraform validate -no-color
      - echo "Running tfsec"
      - cd ../..
      - tfsec terraform/ --format json --out tfsec-report.json || true
      - echo "Running Checkov"
      - checkov -d "terraform/${ENVIRONMENT}" --framework terraform --output cli --output-file-path console --soft-fail || true

  post_build:
    commands:
      - echo "Validation complete"

reports:
  tfsec:
    files:
      - tfsec-report.json
    file-format: "GENERICJSON"
